### ISSUE TITLE
Links broken in Dashboard documentation (V2)

### ISSUE THREAD

**Issue by Vasilievski** [elsa-workflows/elsa-documentation#14]
Hi, 

In the dashboard documentation, the three first links are broken :

[Elsa Server](https://v2.elsaworkflows.io/docs/quickstarts/quickstarts-aspnetcore-server-api-endpoints.md)
[ElsaDashboard.Web](https://github.com/elsa-workflows/elsa-core/tree/master/src/dashboards/aspnetcore/ElsaDashboard)
[ElsaDashboard + Docker](https://v2.elsaworkflows.io/docs/quickstarts/quickstarts/quickstarts-elsa-dashboard-docker)

See you !

**Comment by sfmskywalker** [comment]
Thanks for reporting mate!

Fixed via 56dfe11970f109fc91769da232b9ce422a104487
