### ISSUE TITLE
In the Elsa Documentation for 3.0, in order to create a new user we are supposed to call the following rest endpoint

### ISSUE THREAD

**Issue by Gupta-Krishnaa** [elsa-workflows/elsa-documentation#16]
In the Elsa Documentation for 3.0, in order to create a new user we are supposed to call the following rest endpoint

```
https://server-name/elsa/api/identity/applications \
--header 'Content-Type: application/json' \
--data '{
    "name": "Postman",
    "roles": ["admin"]
}
```

However, it's applicable only for `localhost` as the [documentation](https://v3.elsaworkflows.io/docs/installation/aspnet-apps-workflow-server) states 

> By default, creating applications is allowed for anonymous requests from the localhost.

I would like to host the application on my personal azure platform with App Service which will not have `localhost`. What should be done in that case ?

`cc`: @sfmskywalker @agriffard @VahidNaderi @mohdali

_Originally posted by @Gupta-Krishnaa in https://github.com/elsa-workflows/elsa-documentation/discussions/15_

**Comment by sfmskywalker** [comment]
In an ideal scenario, Elsa Studio would guide users through a setup procedure during its initial launch. This would facilitate the creation of an admin user tailored to the target environment, ensuring a seamless experience.

Currently, Elsa Studio does not possess this feature. As a workaround, I recommend creating the user in a local environment. Once the user is successfully created, you can then migrate the database or the specific database records to your production environment. This method ensures that you have the necessary user configurations in place before deploying to a non-localhost environment like Azure App Service.

It's essential to ensure the security and integrity of your data during this process. Always backup your production database before making any changes and test the migration in a staging environment if possible.
