### ISSUE TITLE
Broken link in Elsa Studio (Stencil)

### ISSUE THREAD

**Issue by jkatsiotis** [elsa-workflows/elsa-documentation#26]
In this page: https://v3.elsaworkflows.io/docs/installation/elsa-studio-stencil

On Deprecation Notice the link is incorrect:

> we recommend using the [Blazor version](https://v3.elsaworkflows.io/docs/installation/elsa-studio) of the workflow designer.

**Comment by sfmskywalker** [comment]
Thanks for reporting!

**Comment by jkatsiotis** [comment]
Still broken :)

**Comment by sfmskywalker** [comment]
You got me - I didn't test 😅
Should be good now, thanks for persisting 👍🏻
