### ISSUE TITLE
v2 documentation links to deprecated npm package

### ISSUE THREAD

**Issue by ElD4n1** [elsa-workflows/elsa-documentation#27]
Hi, i noticed that the "Installing Elsa Dashboard"-section in v2 documentation links to a deprecated npm package of the workflow designer: https://www.npmjs.com/package/@elsa-workflows/elsa-workflow-designer

Should be https://www.npmjs.com/package/@elsa-workflows/elsa-workflows-studio

**Comment by sfmskywalker** [comment]
Great catch, thanks!
