### ISSUE TITLE
Wrong documentation for C# expressions

### ISSUE THREAD

**Issue by LukasBenner** [elsa-workflows/elsa-documentation#63]
The [documentation](https://v3.elsaworkflows.io/docs/expressions/csharp) states that the output of an acticity can be retrieved by calling `Output.From(string, string?)`. This leads to a compilation error stating that OutputProxy has no such method. 

I took a look into the sourcecode and saw that the real method name is `Output.Get(string, string?)`.

**Comment by sfmskywalker** [comment]
Thanks for reporting!

**Comment by sfmskywalker** [comment]
The documentation [has been updated](https://github.com/elsa-workflows/elsa-documentation/pull/52) by @sNakiex.
